spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mes_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: local-mes-qc

    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_efikSZruT

aws:
  sns:
    region: ${AWS_REGION}
    sms-type: Transactional
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  cognito:
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    domain: https://us-east-2efikszrut.auth.us-east-2.amazoncognito.com
    user-pool-id: us-east-2_efikSZruT
    client-id: 4ih0c0267q6mrckj7fdsj2c7ct
    client-secret: gsh0q9k67ffj67mjdrnqhseq7aipvguuhgug92gqjtfon11gq8m
    jwk-url: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_efikSZruT/.well-known/jwks.json
    issuer-url: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_efikSZruT
    audience: 4ih0c0267q6mrckj7fdsj2c7ct

feign:
  client:
    config:
      s3-adapter-service:
        url: http://s3-adapter-service:8083
        connect-timeout: 5000
        read-timeout: 5000

jwt:
  secret: "kLLoGMeKsPCYbcyF5+dxzvUUL7NIMb3TyaNhIGMWU8bkeMWrVzdh7Ufa2RCcqdh0S7eCgDGK23eRYvQyiZ2snw=="
  access_token:
    expiration: 86400000
  refresh_token:
    expiration: 604800000

cors:
  allowed-origins:
    - "*"
  max-age: 60

qc:
  snapshot:
    api:
      url: ${QC_SNAPSHOT_API_URL:http://localhost:8010/api/qc-snapshot}
