spring:
  profiles:
    active: dev

  application:
    name: mes-qc-service

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        transaction.jta.platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  datasource:
    hikari:
      minimum-idle: 10          # Minimum number of idle connections in the pool
      maximum-pool-size: 20     # Maximum number of connections (active + idle)
      idle-timeout: 30000       # 30 seconds - Time a connection can remain idle before being closed
      max-lifetime: 900000      # 15 minutes - Maximum lifetime of a connection
      leak-detection-threshold: 60000  # 60 seconds - Time a connection can be borrowed before flagged as leaked
      connection-timeout: 45000 # 45 seconds - Time to wait for a new connection before timing out
      keepalive-time: 30000

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          localhost: ${EMAIL_REDIRECT_HOST}
          sendpartial: true

server:
  port: 8090
  servlet:
    context-path: /api/qc

  tomcat:
    threads:
      max: 200
    connection-timeout: 20000

java:
  awt:
    headless: false

logging:
  level:
    org.hibernate: WARN
    org.mongodb: WARN
    org.springframework: INFO

management:
  health:
    mail:
      enabled: false
    rabbit:
      enabled: false
    db:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true

  metrics:
    export:
      defaults:
        enabled: true

qc:
  snapshot:
    api:
      url: ${QC_SNAPSHOT_API_URL:http://localhost:8081/api/qc-snapshot}

