spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: {MONGO_URI}
      database: ${MONGO_DB}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: true
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 3000ms
          time-between-eviction-runs: 30000ms

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}

    jackson:
      serialization:
        write-dates-as-timestamps: false

aws:
  sns:
    region: ${AWS_REGION}
    sms-type: Transactional
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  cognito:
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    domain: ${COGNITO_DOMAIN}
    user-pool-id: ${COGNITO_USER_POOL_ID}
    client-id: ${COGNITO_CLIENT_ID}
    client-secret: ${COGNITO_CLIENT_SECRET}
    jwk-url: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
    issuer-url: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
    audience: ${COGNITO_CLIENT_ID}

jwt:
  secret: ${JWT_SECRET}
  access_token:
    expiration: 86400000
  refresh_token:
    expiration: 604800000

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGINS}
  max-age: 3600

qc:
  snapshot:
    api:
      url: ${QC_SNAPSHOT_API_URL}
