spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DB}

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}

    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}

  jackson:
    serialization:
      write-dates-as-timestamps: false

aws:
  sns:
    region: ${AWS_REGION}
    sms-type: Transactional
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  cognito:
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    domain: ${COGNITO_DOMAIN}
    user-pool-id: ${COGNITO_USER_POOL_ID}
    client-id: ${COGNITO_CLIENT_ID}
    client-secret: ${COGNITO_CLIENT_SECRET}
    jwk-url: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}/.well-known/jwks.json
    issuer-url: https://cognito-idp.${AWS_REGION}.amazonaws.com/${COGNITO_USER_POOL_ID}
    audience: ${COGNITO_CLIENT_ID}

feign:
  client:
    config:
      s3-adapter-service:
        url: ${S3_ADAPTER_URL:http://s3-adapter-service:8083}
        connect-timeout: 5000
        read-timeout: 5000

jwt:
  secret: ${JWT_SECRET}
  access_token:
    expiration: 86400000
  refresh_token:
    expiration: 604800000

cors:
  allowed-origins:
    - "*"
  max-age: 60

qc:
  snapshot:
    api:
      url: ${QC_SNAPSHOT_API_URL}
  approval-template:
    mongodb:
      database: ${APPROVAL_TEMPLATE_MONGODB_DATABASE:mes-dev}
